name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ðŸ”§
        run: |
          sudo apt update && sudo apt install reprepro

          # import keys
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > priv.gpg
          gpg2 --import pub.gpg && gpg2 --import priv.gpg
          rm priv.gpg
          
          mkdir incoming
          mv packages/*/*/* incoming/

          reprepro -V processincoming default
          reprepro -V export

          mkdir deploy
          mv dists deploy
          mv lists deploy
          mv pool deploy

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: deploy
          folder: deploy
